name: "Rebase"

"on":
  push:
    branches:
      - main

concurrency:
  group: push-rebase-main
  cancel-in-progress: true

jobs:
  rebase:
    name: "Rebase"
    runs-on: ubuntu-latest
    steps:

      - name: "Rebase all Dependabot's pull requests on every push to the main branch"
        uses: bbeesley/gha-auto-dependabot-rebase@v1.5.160
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: "Rebase all users' pull requests on release push to the main branch"
        uses: peter-evans/rebase@v3.1.0
        with:
          base: main
          exclude-drafts: true
          exclude-labels: dependencies
